//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demolinq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int emp_id { get; set; }
        public string emp_name { get; set; }
        public string emp_job { get; set; }
        public Nullable<int> emp_age { get; set; }
    }
    public class False_Employee : Employee { }
    public class ravivm
    {
        public String name { get; set; }
        public String adderes { get; set; }
        public Nullable<int>  age { get; set; }
    }
}
