//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demolinq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registation
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public Nullable<bool> gender { get; set; }
        public Nullable<bool> isactive { get; set; }
        public string country { get; set; }
        public Nullable<int> age { get; set; }
        public int Role { get; set; }
    }
}
